// <auto-generated />
using System;
using EFCore2017.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore2017.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore2017.EntityModels.Igra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Iznos");

                    b.Property<int>("KorisnikID");

                    b.Property<string>("Naziv");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikID")
                        .IsUnique();

                    b.ToTable("Igre");
                });

            modelBuilder.Entity("EFCore2017.EntityModels.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa");

                    b.Property<string>("Naziv");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("EFCore2017.ViewModels.KorisnikPrikaziViseTabelaViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IgraNaziv");

                    b.Property<int?>("IznosDobitka");

                    b.Property<string>("KorisnikAdresa");

                    b.Property<int>("KorisnikID");

                    b.Property<string>("KorisnikNaziv");

                    b.HasKey("Id");

                    b.ToTable("KorisniciIgreTabela");
                });

            modelBuilder.Entity("EFCore2017.EntityModels.Igra", b =>
                {
                    b.HasOne("EFCore2017.EntityModels.Korisnik")
                        .WithOne("Igra")
                        .HasForeignKey("EFCore2017.EntityModels.Igra", "KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
